### ISSUE TITLE
Running pwg on Linux

### ISSUE THREAD

**Issue by bertt** [gost/play-with-gost#2]
On Linux there is an error when calling some Docker functionality:

```
$ curl http://localhost:50118/api/gost_instance
System.ComponentModel.Win32Exception (0x80004005): No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute()
   at Ductus.FluentDocker.Commands.Machine.Ls()
   at Ductus.FluentDocker.Services.Hosts.Discover()
```

How to fix this?

**Comment by bertt** [comment]
fixed in the fluentlib
